name: Run Underlay

on:
  workflow_call:
    inputs:
      playbook:
        required: true
        type: string
      inventory:
        required: true
        type: string
      extra_vars:
        required: false
        type: string
    secrets:
      VAULT_PASSWORD:
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout underlay
      #  uses: actions/checkout@v4
      #  with:
       #   repository: Devagar-BA/Ansible-underlay
       #   ref: main
       
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

 #     - name: Download inventory
  #      uses: actions/download-artifact@v4
 #       with:
   #       name: overlay-artifacts
      
      - name: Debug repo info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Branch/Ref: $GITHUB_REF"
          ls -l "$GITHUB_WORKSPACE"
      - name: Check roles
        run: ls -R roles



      - name: Run playbook
        run: |
          VAULT_OPT=""
          if [ -f vault_pass.txt ]; then
            VAULT_OPT="--vault-password-file vault_pass.txt"
          fi

          cd $GITHUB_WORKSPACE

          ansible-playbook \
            ${{ inputs.playbook }} \
            -i ${{ inputs.inventory }} \
            -e "${{ inputs.extra_vars }}" \
            $VAULT_OPT
